### ISSUE TITLE
Decoupler drag cube missing comma

### ISSUE THREAD

**Issue by LouisB3** [deimos790/RLA_Continued#1]
Issue summarized here:

> the offending line in the source is thus:
> DRAG_CUBE
> 	{
> 		cube = Default, 0.06135106,0.7812009,0.4141177, 0.06135106,0.7812009,0.4108824, 0.3032565,0.9618634,0.1185349, 0.3032565,0.9619145,0.1185349 0.06135106,0.7811964,0.4108824, 0.06135106,0.7811964,0.4141177, 0,0,0, 0.625,0.09999999,0.6250001
> 	}
> Note carefully at position 12 from the end, a comma is missing. MM is trying to multiply a non-integer and obviously failing. Quick fix is to stick the comma in there to fix that index. I however don't know why it threw two errors, as I can only find that one.

http://forum.kerbalspaceprogram.com/index.php?/topic/133635-rominifork-generic-rescaling-for-when-ro-is-too-heavy/#comment-2576120

Reports courtesy of these folks:

http://forum.kerbalspaceprogram.com/index.php?/topic/81386-11-rla-stockalike-134-25-apr/&do=findComment&comment=2577403

http://forum.kerbalspaceprogram.com/index.php?/topic/81386-11-rla-stockalike-134-25-apr/&do=findComment&comment=2804704

**Comment by deimos790** [comment]
Wow, would not have found that. Thanks!
